import Head from "next/head";
import LeftBar from "../components/leftBar";
import Topbar from "../components/topbar";

export default function Students(): JSX.Element {
  return (
    <div>
      <Head>
        <title>Exam</title>
        <meta name="description" content="Generated by create next app." />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LeftBar />
      <div className="main-body main-body-2">
        <Topbar title="Exam" />
        <div className="container-fluid px-lg-5 px-4">
          <div className="row">
            <div className="col-12 mt-4 px-0 white-card">
              <div className="green-header py-3 px-4">
                <h1 className="my-0">Exams Details</h1>
              </div>
              <div className="px-lg-5 pb-lg-5 p-4">
                <form action="#_">
                  <div className="row pb-5">
                    <div className="col-lg-6 mt-3">
                      <label className="medium">Exam *</label>
                      <input
                        type="text"
                        className="site-input w-100 border px-3 py-2 rounded"
                        defaultValue="Trimestre"
                      />
                    </div>
                    <div className="col-lg-6 mt-3">
                      <label className="medium">Semester *</label>
                      <input
                        type="text"
                        className="site-input w-100 border px-3 py-2 rounded"
                        defaultValue="03 Semestre"
                      />
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
          <div className="d-sm-flex justify-content-end align-items-center py-4">
            <button className="transparent-btn py-2 px-4 mt-3">Save as Draft</button>
            <button className="site-btn px-5 py-2 mt-3">Submit</button>
          </div>
        </div>
      </div>
    </div>
  );
}
