import Head from "next/head";
import LeftBar from "../components/leftBar";
import Topbar from "../components/topbar";

export default function Students(): JSX.Element {
  return (
    <div>
      <Head>
        <title>Finance</title>
        <meta name="description" content="Generated by create next app." />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LeftBar />
      <div className="main-body main-body-2">
        <Topbar title="Finance" />
        <div className="container-fluid px-lg-5 px-4">
          <div className="row">
            <div className="col-12 p-lg-5 mt-4 p-4">
              <div className="row">
                <div className="col-lg-3">
                  <div className="media py-4 white-card px-3">
                    <img src="images/students.png" alt="" className="img-fluid" />
                    <div className="media-body ml-3">
                      <p className="grey-text mb-0">Students</p>
                      <h3 className="mb-0">932</h3>
                      <p className="grey-text p-sm mb-0">
                        <span className="blue-text">+10% </span> than last month
                      </p>
                    </div>
                  </div>
                </div>
                <div className="col-lg-3">
                  <div className="media py-4 white-card px-3">
                    <img src="images/teachers.png" alt="" className="img-fluid" />
                    <div className="media-body ml-3">
                      <p className="grey-text mb-0">Teachers</p>
                      <h3 className="mb-0">50</h3>
                      <p className="grey-text p-sm mb-0">
                        <span className="red-text">-0.5% </span> than last month
                      </p>
                    </div>
                  </div>
                </div>
                <div className="col-lg-6">
                  <div className="media py-4 white-card px-3">
                    <img src="images/balance.png" alt="" className="img-fluid" />
                    <div className="media-body ml-3">
                      <p className="grey-text mb-0">School Balance</p>
                      <h3 className="mb-0">$123,456</h3>
                      <p className="grey-text mb-0">
                        <span className="blue-text">+23% </span> than last month
                      </p>
                    </div>
                    <img src="images/graph-sm.png" alt="" className="img-fluid ml-3" />
                  </div>
                </div>
              </div>
            </div>
            <div className="col-12">
              <img src="images/graph.png" alt="" className="img-fluid w-100" />
            </div>
            <div className="col-lg-7">
              <div className="mt-4 p-4 white-card">
                <h1 className="mb-0">Unpaid Student Intuition</h1>
                <div className="table-responsive">
                  <table className="table dash-table">
                    <thead>
                      <tr>
                        <th />
                        <th />
                        <th />
                        <th />
                        <th />
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>
                          <div className="media align-items-center">
                            <img src="images/student-1.png" alt="" className="img-fluid mr-2" />
                            <div className="media-body">
                              <p className="p-lg mb-0 semi-bold">Samantha W.</p>
                            </div>
                          </div>
                        </td>
                        <td>
                          <p className="p-lg mb-0 semi-bold blue-text">ID 123456789</p>
                        </td>
                        <td>
                          <div className="media align-items-center">
                            <img src="images/class.png" alt="" className="img-fluid mr-2" />
                            <div className="media-body">
                              <p className="grey-text mb-0">Class</p>
                              <p className="p-lg mb-0 semi-bold">VII A</p>
                            </div>
                          </div>
                        </td>
                        <td>
                          <p className="p-lg mb-0 semi-bold">$ 50,036</p>
                        </td>
                        <td>
                          <div className="dropdown">
                            <button
                              className="transparent-btn"
                              type="button"
                              id="dropdownMenuButton"
                              data-toggle="dropdown"
                              aria-haspopup="true"
                              aria-expanded="false"
                            >
                              <i className="fas fa-ellipsis-h" />
                            </button>
                            <div className="dropdown-menu" aria-labelledby="dropdownMenuButton">
                              <a className="dropdown-item" href="#">
                                Action
                              </a>
                              <a className="dropdown-item" href="#">
                                Another action
                              </a>
                              <a className="dropdown-item" href="#">
                                Something else here
                              </a>
                            </div>
                          </div>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <div className="media align-items-center">
                            <img src="images/student-1.png" alt="" className="img-fluid mr-2" />
                            <div className="media-body">
                              <p className="p-lg mb-0 semi-bold">Samantha W.</p>
                            </div>
                          </div>
                        </td>
                        <td>
                          <p className="p-lg mb-0 semi-bold blue-text">ID 123456789</p>
                        </td>
                        <td>
                          <div className="media align-items-center">
                            <img src="images/class.png" alt="" className="img-fluid mr-2" />
                            <div className="media-body">
                              <p className="grey-text mb-0">Class</p>
                              <p className="p-lg mb-0 semi-bold">VII A</p>
                            </div>
                          </div>
                        </td>
                        <td>
                          <p className="p-lg mb-0 semi-bold">$ 50,036</p>
                        </td>
                        <td>
                          <div className="dropdown">
                            <button
                              className="transparent-btn"
                              type="button"
                              id="dropdownMenuButton"
                              data-toggle="dropdown"
                              aria-haspopup="true"
                              aria-expanded="false"
                            >
                              <i className="fas fa-ellipsis-h" />
                            </button>
                            <div className="dropdown-menu" aria-labelledby="dropdownMenuButton">
                              <a className="dropdown-item" href="#">
                                Action
                              </a>
                              <a className="dropdown-item" href="#">
                                Another action
                              </a>
                              <a className="dropdown-item" href="#">
                                Something else here
                              </a>
                            </div>
                          </div>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <div className="media align-items-center">
                            <img src="images/student-1.png" alt="" className="img-fluid mr-2" />
                            <div className="media-body">
                              <p className="p-lg mb-0 semi-bold">Samantha W.</p>
                            </div>
                          </div>
                        </td>
                        <td>
                          <p className="p-lg mb-0 semi-bold blue-text">ID 123456789</p>
                        </td>
                        <td>
                          <div className="media align-items-center">
                            <img src="images/class.png" alt="" className="img-fluid mr-2" />
                            <div className="media-body">
                              <p className="grey-text mb-0">Class</p>
                              <p className="p-lg mb-0 semi-bold">VII A</p>
                            </div>
                          </div>
                        </td>
                        <td>
                          <p className="p-lg mb-0 semi-bold">$ 50,036</p>
                        </td>
                        <td>
                          <div className="dropdown">
                            <button
                              className="transparent-btn"
                              type="button"
                              id="dropdownMenuButton"
                              data-toggle="dropdown"
                              aria-haspopup="true"
                              aria-expanded="false"
                            >
                              <i className="fas fa-ellipsis-h" />
                            </button>
                            <div className="dropdown-menu" aria-labelledby="dropdownMenuButton">
                              <a className="dropdown-item" href="#">
                                Action
                              </a>
                              <a className="dropdown-item" href="#">
                                Another action
                              </a>
                              <a className="dropdown-item" href="#">
                                Something else here
                              </a>
                            </div>
                          </div>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <div className="media align-items-center">
                            <img src="images/student-1.png" alt="" className="img-fluid mr-2" />
                            <div className="media-body">
                              <p className="p-lg mb-0 semi-bold">Samantha W.</p>
                            </div>
                          </div>
                        </td>
                        <td>
                          <p className="p-lg mb-0 semi-bold blue-text">ID 123456789</p>
                        </td>
                        <td>
                          <div className="media align-items-center">
                            <img src="images/class.png" alt="" className="img-fluid mr-2" />
                            <div className="media-body">
                              <p className="grey-text mb-0">Class</p>
                              <p className="p-lg mb-0 semi-bold">VII A</p>
                            </div>
                          </div>
                        </td>
                        <td>
                          <p className="p-lg mb-0 semi-bold">$ 50,036</p>
                        </td>
                        <td>
                          <div className="dropdown">
                            <button
                              className="transparent-btn"
                              type="button"
                              id="dropdownMenuButton"
                              data-toggle="dropdown"
                              aria-haspopup="true"
                              aria-expanded="false"
                            >
                              <i className="fas fa-ellipsis-h" />
                            </button>
                            <div className="dropdown-menu" aria-labelledby="dropdownMenuButton">
                              <a className="dropdown-item" href="#">
                                Action
                              </a>
                              <a className="dropdown-item" href="#">
                                Another action
                              </a>
                              <a className="dropdown-item" href="#">
                                Something else here
                              </a>
                            </div>
                          </div>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <div className="media align-items-center">
                            <img src="images/student-1.png" alt="" className="img-fluid mr-2" />
                            <div className="media-body">
                              <p className="p-lg mb-0 semi-bold">Samantha W.</p>
                            </div>
                          </div>
                        </td>
                        <td>
                          <p className="p-lg mb-0 semi-bold blue-text">ID 123456789</p>
                        </td>
                        <td>
                          <div className="media align-items-center">
                            <img src="images/class.png" alt="" className="img-fluid mr-2" />
                            <div className="media-body">
                              <p className="grey-text mb-0">Class</p>
                              <p className="p-lg mb-0 semi-bold">VII A</p>
                            </div>
                          </div>
                        </td>
                        <td>
                          <p className="p-lg mb-0 semi-bold">$ 50,036</p>
                        </td>
                        <td>
                          <div className="dropdown">
                            <button
                              className="transparent-btn"
                              type="button"
                              id="dropdownMenuButton"
                              data-toggle="dropdown"
                              aria-haspopup="true"
                              aria-expanded="false"
                            >
                              <i className="fas fa-ellipsis-h" />
                            </button>
                            <div className="dropdown-menu" aria-labelledby="dropdownMenuButton">
                              <a className="dropdown-item" href="#">
                                Action
                              </a>
                              <a className="dropdown-item" href="#">
                                Another action
                              </a>
                              <a className="dropdown-item" href="#">
                                Something else here
                              </a>
                            </div>
                          </div>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <div className="d-lg-flex align-items-center justify-content-between">
                  <p className="mb-0 mt-3">Showing 1 to 10 of 42 entries</p>
                  <nav className="mt-3" aria-label="Page navigation example">
                    <ul className="pagination justify-content-end">
                      <li className="page-item disabled">
                        <a className="page-link" href="#" tabIndex={-1} aria-disabled="true">
                          <i className="fas fa-caret-left" />
                        </a>
                      </li>
                      <li className="page-item active">
                        <a className="page-link pagi-pages" href="#">
                          1
                        </a>
                      </li>
                      <li className="page-item">
                        <a className="page-link pagi-pages" href="#">
                          2
                        </a>
                      </li>
                      <li className="page-item">
                        <a className="page-link pagi-pages" href="#">
                          3
                        </a>
                      </li>
                      <li className="page-item">
                        <a className="page-link" href="#">
                          <i className="fas fa-caret-right" />
                        </a>
                      </li>
                    </ul>
                  </nav>
                </div>
              </div>
            </div>
            <div className="col-lg-5">
              <div className="mt-4 p-4 white-card">
                <h1 className="mb-0">School Expense</h1>
                <div className="table-responsive">
                  <table className="table dash-table">
                    <thead>
                      <tr>
                        <th />
                        <th />
                        <th />
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>
                          <div className="media align-items-center">
                            <img src="images/finance.png" alt="" className="img-fluid mr-2" />
                            <div className="media-body">
                              <p className="mb-0 semi-bold">#123456789</p>
                              <p className="p-sm mb-0 grey-text">2 March 2021, 13:45 PM</p>
                            </div>
                          </div>
                        </td>
                        <td>
                          <p className="p-lg mb-0 semi-bold">$ 50,036</p>
                        </td>
                        <td>
                          <p className="p-lg blue-text mb-0 semi-bold">Completed</p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <div className="media align-items-center">
                            <img src="images/finance.png" alt="" className="img-fluid mr-2" />
                            <div className="media-body">
                              <p className="mb-0 semi-bold">#123456789</p>
                              <p className="p-sm mb-0 grey-text">2 March 2021, 13:45 PM</p>
                            </div>
                          </div>
                        </td>
                        <td>
                          <p className="p-lg mb-0 semi-bold">$ 50,036</p>
                        </td>
                        <td>
                          <p className="p-lg grey-text mb-0 semi-bold">Pending</p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <div className="media align-items-center">
                            <img src="images/finance.png" alt="" className="img-fluid mr-2" />
                            <div className="media-body">
                              <p className="mb-0 semi-bold">#123456789</p>
                              <p className="p-sm mb-0 grey-text">2 March 2021, 13:45 PM</p>
                            </div>
                          </div>
                        </td>
                        <td>
                          <p className="p-lg mb-0 semi-bold">$ 50,036</p>
                        </td>
                        <td>
                          <p className="p-lg red-text mb-0 semi-bold">Cancelled</p>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <div className="media align-items-center">
                            <img src="images/finance.png" alt="" className="img-fluid mr-2" />
                            <div className="media-body">
                              <p className="mb-0 semi-bold">#123456789</p>
                              <p className="p-sm mb-0 grey-text">2 March 2021, 13:45 PM</p>
                            </div>
                          </div>
                        </td>
                        <td>
                          <p className="p-lg mb-0 semi-bold">$ 50,036</p>
                        </td>
                        <td>
                          <p className="p-lg blue-text mb-0 semi-bold">Completed</p>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <div className="d-lg-flex align-items-center justify-content-between">
                  <p className="mb-0 mt-3">Showing 1 to 10 of 42 entries</p>
                  <nav className="mt-3" aria-label="Page navigation example">
                    <ul className="pagination justify-content-end">
                      <li className="page-item disabled">
                        <a className="page-link" href="#" tabIndex={-1} aria-disabled="true">
                          <i className="fas fa-caret-left" />
                        </a>
                      </li>
                      <li className="page-item active">
                        <a className="page-link pagi-pages" href="#">
                          1
                        </a>
                      </li>
                      <li className="page-item">
                        <a className="page-link pagi-pages" href="#">
                          2
                        </a>
                      </li>
                      <li className="page-item">
                        <a className="page-link pagi-pages" href="#">
                          3
                        </a>
                      </li>
                      <li className="page-item">
                        <a className="page-link" href="#">
                          <i className="fas fa-caret-right" />
                        </a>
                      </li>
                    </ul>
                  </nav>
                </div>
              </div>
            </div>
          </div>
        </div>{" "}
      </div>
    </div>
  );
}
