import Head from "next/head";
import React from "react";
import LeftBar from "../components/leftBar";
import Topbar from "../components/topbar";
import { useDropzone } from "react-dropzone";

export default function Students(): JSX.Element {
  const onDrop = React.useCallback((acceptedFiles) => {
    alert();
    // Do something with the files
  }, []);
  const { getRootProps, getInputProps, isDragActive } = useDropzone({ onDrop });

  return (
    <div>
      <Head>
        <title>New Students</title>
        <meta name="description" content="Generated by create next app." />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LeftBar />
      <div className="main-body main-body-2">
        <Topbar title="Students" />
        <div className="container-fluid px-lg-5 px-4">
          <div className="row">
            <div className="col-12 mt-4 px-0 white-card">
              <div className="green-header py-3 px-4">
                <h1 className="my-0">Student Details</h1>
              </div>
              <div className="p-lg-5 p-4">
                <form action="#_">
                  <div className="row">
                    <div className="col-lg-3">
                      <label className="medium">Photo*</label>
                      <label className="d-block">
                        <div {...getRootProps()} className="dashed-bg text-center py-5">
                          <p className="grey-text mb-0">
                            Drag and drop or <br /> click here to select file
                          </p>
                        </div>
                      </label>
                      <div className="d-none">
                        <input {...getRootProps()} type="file" />
                      </div>
                    </div>
                    <div className="col-lg-9 col-12">
                      <div className="row">
                        <div className="col-lg-6 mt-3">
                          <label className="medium">Full Name*</label>
                          <input
                            type="text"
                            className="site-input w-100 border px-3 py-2 rounded"
                            defaultValue="Samantha"
                          />
                        </div>
                        <div className="col-lg-6 mt-3">
                          <label className="medium">Last Name *</label>
                          <input
                            type="text"
                            className="site-input w-100 border px-3 py-2 rounded"
                            defaultValue="William"
                          />
                        </div>
                        <div className="col-lg-6 mt-3">
                          <label className="medium mb-0">Date &amp; Place of Birth *</label>
                          <div className="row">
                            <div className="col-md-6 mt-2">
                              <input type="date" className="site-input w-100 border px-3 py-2 rounded" />
                            </div>
                            <div className="col-md-6 mt-2">
                              <input
                                type="text"
                                defaultValue="Jakarta"
                                className="site-input w-100 border px-3 py-2 rounded"
                              />
                            </div>
                          </div>
                        </div>
                        <div className="col-lg-6 mt-3">
                          <label className="medium">Parent Name *</label>
                          <input
                            type="number"
                            className="site-input w-100 border px-3 py-2 rounded"
                            defaultValue="Mana William"
                          />
                        </div>
                        <div className="col-lg-6 mt-3">
                          <label className="medium">Email *</label>
                          <input
                            type="email"
                            className="site-input w-100 border px-3 py-2 rounded"
                            defaultValue="william@email.com"
                          />
                        </div>
                        <div className="col-lg-6 mt-3">
                          <label className="medium">Phone *</label>
                          <input
                            type="number"
                            className="site-input w-100 border px-3 py-2 rounded"
                            defaultValue={123456789}
                          />
                        </div>
                        <div className="col-lg-6 mt-3">
                          <label className="medium">Address *</label>
                          <textarea
                            className="site-input w-100 border px-3 py-2 rounded"
                            rows={7}
                            defaultValue={
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. \n                                        "
                            }
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
            <div className="col-12 mt-4 px-0 white-card">
              <div className="green-header py-3 px-4">
                <h1 className="my-0">Parent Details</h1>
              </div>
              <div className="p-lg-5 p-4">
                <form action="#_">
                  <div className="row">
                    <div className="col-lg-6 mt-3">
                      <label className="medium">Fater Name*</label>
                      <input type="text" className="site-input w-100 border px-3 py-2 rounded" defaultValue="William" />
                    </div>
                    <div className="col-lg-6 mt-3">
                      <label className="medium">Mother Name *</label>
                      <input type="text" className="site-input w-100 border px-3 py-2 rounded" defaultValue="Mana" />
                    </div>
                    <div className="col-lg-6 mt-3">
                      <label className="medium">Email *</label>
                      <input
                        type="email"
                        className="site-input w-100 border px-3 py-2 rounded"
                        defaultValue="william@email.com"
                      />
                    </div>
                    <div className="col-lg-6 mt-3">
                      <label className="medium">Phone *</label>
                      <input
                        type="number"
                        className="site-input w-100 border px-3 py-2 rounded"
                        defaultValue={123456789}
                      />
                    </div>
                    <div className="col-lg-6 mt-3">
                      <label className="medium">Address *</label>
                      <textarea
                        className="site-input w-100 border px-3 py-2 rounded"
                        rows={7}
                        defaultValue={
                          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. \n                                "
                        }
                      />
                    </div>
                    <div className="col-lg-6 mt-3">
                      <label className="medium">Payments *</label>
                      <div className="d-flex align-items-center">
                        <input type="radio" />
                        <label className="ml-2 mb-0">Cash</label>
                        <input type="radio" className="ml-4" />
                        <label className="ml-2 mb-0">Debit</label>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
          <div className="d-sm-flex justify-content-end align-items-center py-4">
            <button className="transparent-btn py-2 px-4 mt-3">Save as Draft</button>
            <button className="site-btn px-5 py-2 mt-3">Submit</button>
          </div>
        </div>{" "}
      </div>
    </div>
  );
}
