import Head from "next/head";
import LeftBar from "../components/leftBar";
import Topbar from "../components/topbar";

export default function Students(): JSX.Element {
  return (
    <div>
      <Head>
        <title>Students</title>
        <meta name="description" content="Generated by create next app." />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LeftBar />
      <div className="main-body main-body-2">
        <Topbar title="Add New Teacher" />
        <div className="container-fluid px-lg-5 px-4">
          <div className="row">
            <div className="col-12 mt-4 px-0 white-card">
              <div className="green-header py-3 px-4">
                <h1 className="my-0">Personal Details</h1>
              </div>
              <div className="px-lg-5 pb-lg-5 p-4">
                <form action="#_">
                  <div className="row">
                    <div className="col-lg-6 mt-3">
                      <label className="medium">First Name*</label>
                      <input type="text" className="site-input w-100 border px-3 py-2 rounded" defaultValue="Maria" />
                    </div>
                    <div className="col-lg-6 mt-3">
                      <label className="medium">Last Name *</label>
                      <input
                        type="text"
                        className="site-input w-100 border px-3 py-2 rounded"
                        defaultValue="Historia"
                      />
                    </div>
                    <div className="col-lg-6 mt-3">
                      <label className="medium">Phone *</label>
                      <input
                        type="number"
                        className="site-input w-100 border px-3 py-2 rounded"
                        defaultValue={123456789}
                      />
                    </div>
                    <div className="col-lg-6 mt-3">
                      <label className="medium">Photo*</label>
                      <label className="d-block">
                        <div className="dashed-bg photo-dashed text-center">
                          <p className="grey-text mb-0">
                            Drag and drop or <br /> click here to select file
                          </p>
                        </div>
                      </label>
                      <div className="d-none">
                        <input type="file" id="upload-now" />
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
            <div className="col-12 mt-4 px-0 white-card">
              <div className="green-header py-3 px-4">
                <h1 className="my-0">Login's Credentials</h1>
              </div>
              <div className="px-lg-5 pb-lg-5 p-4">
                <form action="#_">
                  <div className="row">
                    <div className="col-lg-6 mt-3">
                      <label className="medium">Company's Code *</label>
                      <input
                        type="number"
                        className="site-input w-100 border px-3 py-2 rounded"
                        defaultValue={267777318}
                      />
                    </div>
                    <div className="col-lg-6 mt-3">
                      <label className="medium">Username *</label>
                      <input
                        type="text"
                        className="site-input w-100 border px-3 py-2 rounded"
                        defaultValue="John Doe"
                      />
                    </div>
                    <div className="col-lg-6 mt-3">
                      <label className="medium">Password *</label>
                      <div className="position-relative">
                        <input
                          type="password"
                          className="site-input w-100 border px-3 py-2 rounded"
                          defaultValue={123456789}
                        />
                        <div className="right-icon">
                          <i className="fas fa-eye" />
                        </div>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
            <div className="col-12 mt-4 px-0 white-card">
              <div className="green-header py-3 px-4">
                <h1 className="my-0">Timetable</h1>
              </div>
              <div className="px-lg-5 pb-lg-5 p-4">
                <form action="#_">
                  <div className="row">
                    <div className="col-lg-6 mt-3">
                      <label className="medium">Classroom *</label>
                      <input
                        type="number"
                        className="site-input w-100 border px-3 py-2 rounded"
                        defaultValue={267777318}
                      />
                    </div>
                    <div className="col-lg-6 mt-3">
                      <label className="medium">Description *</label>
                      <input
                        type="text"
                        className="site-input w-100 border px-3 py-2 rounded"
                        defaultValue="Lorem Ipsum"
                      />
                    </div>
                    <div className="col-lg-6 mt-3">
                      <label className="medium">Start Time *</label>
                      <input type="time" className="site-input w-100 border px-3 py-2 rounded" />
                    </div>
                    <div className="col-lg-6 mt-3">
                      <label className="medium">End Time *</label>
                      <input type="time" className="site-input w-100 border px-3 py-2 rounded" />
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
          <div className="d-sm-flex justify-content-end align-items-center py-4">
            <button className="transparent-btn py-2 px-4 mt-3">Save as Draft</button>
            <button className="site-btn px-5 py-2 mt-3">Submit</button>
          </div>
        </div>
      </div>
    </div>
  );
}
