import Head from "next/head";
import LeftBar from "../components/leftBar";
import Topbar from "../components/topbar";

export default function Students(): JSX.Element {
  return (
    <div>
      <Head>
        <title>Notification & Latest Activity</title>
        <meta name="description" content="Generated by create next app." />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LeftBar />
      <div className="main-body main-body-2">
        <Topbar title="Notification & Latest Activity" />
        <div className="container-fluid px-lg-5 px-4">
          <div className="row">
            <div className="col-12 p-lg-5 mt-2 p-4 white-card">
              <p className="p-lg semi-bold mb-0">Today</p>
              <div className="ml-3">
                <p className="grey-text mt-3 mb-0">Monday, June 31 2020</p>
                <p className="mt-2 mb-0">
                  <span className="semi-bold">Karen Hope</span> has created new task at HIstory Lesson
                </p>
                <p className="grey-text mt-3 mb-0">Monday, June 31 2020</p>
                <p className="mt-2 mb-0">
                  <span className="semi-bold pink-text">[Reminder]</span> Due date of{" "}
                  <span className="semi-bold pink-text"> Science Homework</span> task will be coming
                </p>
                <p className="grey-text mt-3 mb-0">Monday, June 31 2020</p>
                <p className="mt-2 mb-0">
                  <span className="semi-bold">Tony Soap </span> commented at{" "}
                  <span className="semi-bold pink-text"> Science Homework</span>
                </p>
                <p className="grey-text mt-3 mb-0">Monday, June 31 2020</p>
                <p className="mt-2 mb-0">
                  <span className="semi-bold">Samantha William </span> add 4 files on{" "}
                  <span className="semi-bold"> Art Class </span>
                </p>
                <div className="row">
                  <div className="col-lg-3 mt-3">
                    <img src="images/noti-1.png" alt="" className="img-fluid" />
                  </div>
                  <div className="col-lg-3 mt-3">
                    <img src="images/noti-2.png" alt="" className="img-fluid" />
                  </div>
                  <div className="col-lg-3 mt-3">
                    <img src="images/noti-3.png" alt="" className="img-fluid" />
                  </div>
                  <div className="col-lg-3 mt-3">
                    <img src="images/noti-4.png" alt="" className="img-fluid" />
                  </div>
                </div>
              </div>
              <p className="p-lg mt-4 semi-bold mb-0">Yesterday</p>
              <div className="ml-3">
                <p className="grey-text mt-3 mb-0">Monday, June 31 2020</p>
                <p className="mt-2 mb-0">
                  <span className="semi-bold d-blue-text">Karen Hope</span> has created new task at HIstory Lesson
                </p>
                <p className="grey-text mt-3 mb-0">Monday, June 31 2020</p>
                <p className="mt-2 mb-0">
                  <span className="semi-bold pink-text">[Reminder]</span> Due date of{" "}
                  <span className="semi-bold l-yellow-text"> Science Homework</span> task will be coming
                </p>
                <p className="grey-text mt-3 mb-0">Monday, June 31 2020</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
